# Generated by Django 4.1.3 on 2022-11-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('airplane_id', models.AutoField(primary_key=True, serialize=False)),
                ('airplane_number', models.CharField(max_length=20)),
                ('manufacturer_name', models.CharField(max_length=45)),
                ('model_name', models.CharField(max_length=20)),
                ('sub_model_name', models.CharField(max_length=20)),
            ],
        ),
    ]
