# Generated by Django 4.1.3 on 2022-11-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=45)),
                ('other_names', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('passport_no', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=45)),
                ('country_code', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=200)),
                ('other_names', models.CharField(max_length=20)),
                ('national_status', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('id_no', models.IntegerField()),
                ('profession', models.CharField(max_length=20)),
                ('sex', models.BooleanField()),
                ('place_of_birth', models.CharField(max_length=20)),
                ('date_of_issue', models.DateField()),
                ('date_of_expiry', models.DateField()),
                ('authority', models.CharField(max_length=20)),
            ],
        ),
    ]
