# Generated by Django 4.1.3 on 2022-11-27 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_flightschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('airplane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.airplane')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.class')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('employee_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('FULL_TIME', 'FULL_TIME'), ('FULL_TIME', 'PART_TIME'), ('CANCEL', 'Cancel')], default='FULL_TIME', max_length=10)),
                ('flight_schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flightschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('RESERVE', 'RESERVE')], default='RESERVE', max_length=10)),
                ('airplane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.airplane')),
                ('class_id', models.ForeignKey(db_column='airplane_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.class')),
                ('seat_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.seat')),
            ],
        ),
    ]
