# Generated by Django 4.1.3 on 2022-11-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_class_seat_employeeschedule_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='airplane_id',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='class_id',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
