# Generated by Django 4.1.3 on 2022-11-27 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_class_airplane_id_remove_seat_class_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('airplane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.airplane')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.class')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('RESERVE', 'RESERVE')], default='RESERVE', max_length=10)),
                ('airplane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.airplane')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.class')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.seat')),
            ],
        ),
    ]
