# Generated by Django 4.1.3 on 2022-11-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='class_id',
        ),
    ]
