# Generated by Django 4.1.3 on 2022-11-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_booking_class_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSchedule',
        ),
    ]
