# Generated by Django 4.1.3 on 2022-11-27 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_delete_employeeschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('employee_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('FULL_TIME', 'FULL_TIME'), ('FULL_TIME', 'PART_TIME'), ('CANCEL', 'Cancel')], default='FULL_TIME', max_length=10)),
                ('flight_schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flightschedule')),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.passenger')),
            ],
        ),
    ]
