# Generated by Django 4.1.3 on 2022-11-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_passenger_id_booking_passenger_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='airplane_id',
            new_name='airplane',
        ),
        migrations.RenameField(
            model_name='employeeschedule',
            old_name='flight_schedule_id',
            new_name='flight_schedule',
        ),
        migrations.RenameField(
            model_name='employeeschedule',
            old_name='passenger_id',
            new_name='passenger',
        ),
        migrations.RenameField(
            model_name='flightschedule',
            old_name='airplane_id',
            new_name='airplane',
        ),
    ]
