# Generated by Django 4.1.3 on 2022-11-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
