# Generated by Django 4.1.3 on 2022-11-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_booking_seat_delete_seat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
