# Generated by Django 4.1.3 on 2022-11-28 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='airplane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.airplane'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pilot_rating',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_name',
            field=models.CharField(choices=[('HOST', 'HOST'), ('PILOT', 'PILOT'), ('OTHER', 'OTHER')], default='OTHER', max_length=10),
        ),
    ]
