# Generated by Django 4.1.3 on 2022-11-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_employee_airplane_employee_pilot_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('DIRECT', 'DIRECT'), ('CONNECT', 'CONNECT')], default='RESERVE', max_length=10),
        ),
    ]
