# Generated by Django 4.1.3 on 2022-11-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_booking_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSchedule',
        ),
    ]
